server:
  port : 8090
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://xx.xxx.xxx.xxx:3307/maptest?characterEncoding=utf-8&useSSL=false
    username: root
    password: mypassword
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: xx.xxx.xxx.xxx
    port: 6379
    timeout: 30000
    password: mypassword

#redis查询日志
logging:
  config: classpath:log4j2.xml
  level:
    com.ops.**.mapper: debug
mybatis:
  type-aliases-package: com.ops.**.pojo
  mapper-locations: classpath:mybatis/mapper/ops/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


